### ISSUE TITLE
Keep showing Error: cannot use this on ....

### ISSUE THREAD

**Issue by ltduy1990** [narunlifescience/AlphaPlot#19] opened 2020-07-09 19:39 UTC
Hello, 
I really like your app. How nice its GUI is.
I have just tested the newest ver. [1.0.11] and I found some issues.
(1) When I dragged the graph, modified some parameters, and added arrow/text in the 2D graph, the error keeps showing up.
(2) There is no option to delete or insert arbitrary cell(s) in the data sheet {like in EXCEL}. Thus, It is difficult to remove cells in one column but not delete others in the same row.
(3) The reference settings for graph types in EDIT/REFERENCES cannot be saved. It reset automatically after I clicked on Apply or OK. Therefore, adjusting graph display size is painful.

I hope that my report is helpful for the improvement of AlphaPlot.
If you need further information, feel free to contact me!
Have a great day! 
LT. DUY

**Comment by narunlifescience** [comment] 2020-07-09 20:05
Thank you for reporting the issue. Alphaplot is under active development. 
1)  It would be more helpful if you could specify the exact error messages you are getting. It is also possible that these issues are fixed in the master branch. I encourage you to post the error message and how you ended up with the error so that I can have a look.
2) Unfortunately, that's how AlphaPlot is designed to function. This is because the table or matrix represents a database table rather than an excel sheet. I recommend you to read https://alphaplot.sourceforge.io/wiki/index.php/Table to get an idea.
3) yes that's broken in the release. I am in the process of rewriting this section with better user customization and UI. This will get fixed in the next release. 
for adjusting Graph display size, I suggest you select the graph window as active window -> click canvas in property editor and change the width and height property according to your needs.

Thank you for reporting.

**Comment by ltduy1990** [comment] 2020-07-09 20:32
Hi,
Thanks for your prompt response.
I saw the error popup many times. I summarized some of them in the enclosed
PPTX file. Please check it out!

*LT. Duy*
Department of Materials Science and Engineering,
Ajou University, 206 Worldcup-ro, Yeongtong-gu, Suwon-si, 16499, Republic
of Korea.
Cell phone: +82-10-6700-1980

**Comment by narunlifescience** [comment] 2020-07-09 20:39
I am unable to find the mentioned pptx file. could you please send it to n.arun.lifescience@gmail.com as an attachment..

**Comment by narunlifescience** [comment] 2020-07-10 06:13
![Alphaplot-error](https://user-images.githubusercontent.com/11949260/87121579-a52d8080-c2a0-11ea-8a3d-62c692eecbed.png)
The error is designed to pop up when users try to copy selection(ctrl + C), cut selection(ctrl + X), paste selection(ctrl + V) or clear selection (backspace) when the graph 2D window is the active window. these operations are only supported in tables, matrices, and notes. please make sure that you are not using these actions or their keyboard shortcuts on a graph2D window. Could you please check if this resolves the issue and report back?
 
I am unable to reproduce this error in other scenarios as you described in the pptx file in both windows and Linux.

**Comment by narunlifescience** [comment] 2020-07-20 23:02
commit  ae7de2e adds a glowing indicator to currently active window

**Comment by narunlifescience** [comment] 2022-01-21 05:15
fixed in new release v1.02

**Closed by narunlifescience** 2022-01-21 05:15 UTC
Labels: bug
